// <auto-generated />
using System;
using Kokbok.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kokbok.Api.Database.Migrations;

[DbContext(typeof(KokbokDbContext))]
[Migration("20260722102523_AddRecipes")]
partial class _20260722102523_AddRecipes
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118");

        modelBuilder.Entity("AssetImages", b =>
            {
                b.Property<Guid>("AssetsId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("ImagesId")
                    .HasColumnType("TEXT");

                b.HasKey("AssetsId", "ImagesId");

                b.HasIndex("ImagesId");

                b.ToTable("AssetImages");
            });

        modelBuilder.Entity("Kokbok.Api.Models.AmountValue", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Discriminator")
                    .IsRequired()
                    .HasMaxLength(13)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("AmountValue");

                b.HasDiscriminator<string>("Discriminator").IsComplete(true).HasValue("AmountValue");

                b.UseTphMappingStrategy();
            });

        modelBuilder.Entity("Kokbok.Api.Models.Asset", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Filename")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("RemovedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UploadedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UploadedById")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("UploadedById");

                b.ToTable("Assets");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Ingredient", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid?>("SectionId")
                    .HasColumnType("TEXT")
                    .HasColumnName("Section<Ingredient>Id");

                b.HasKey("Id");

                b.HasIndex("SectionId");

                b.ToTable("Ingredient");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Instruction", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("SectionId")
                    .HasColumnType("TEXT")
                    .HasColumnName("Section<Instruction>Id");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SectionId");

                b.ToTable("Instruction");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Recipe", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("ImageId")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("OwnerId")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("SourceId")
                    .HasColumnType("TEXT");

                b.Property<int>("Visibility")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ImageId");

                b.HasIndex("OwnerId");

                b.HasIndex("SourceId");

                b.ToTable("Recipes");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Section<Kokbok.Api.Models.Ingredient>", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("RecipeId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("RecipeId");

                b.ToTable("Section<Ingredient>");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Section<Kokbok.Api.Models.Instruction>", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("RecipeId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("RecipeId");

                b.ToTable("Section<Instruction>");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Source", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Discriminator")
                    .IsRequired()
                    .HasMaxLength(13)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Source");

                b.HasDiscriminator<string>("Discriminator").IsComplete(true).HasValue("Source");

                b.UseTphMappingStrategy();
            });

        modelBuilder.Entity("Kokbok.Api.Models.User", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("INTEGER");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("PasswordHash")
                    .HasColumnType("TEXT");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("TEXT");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("INTEGER");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("TEXT");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.ToTable("AspNetUsers");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClaimType")
                    .HasColumnType("TEXT");

                b.Property<string>("ClaimValue")
                    .HasColumnType("TEXT");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClaimType")
                    .HasColumnType("TEXT");

                b.Property<string>("ClaimValue")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("TEXT");

                b.Property<string>("ProviderKey")
                    .HasColumnType("TEXT");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("TEXT");

                b.Property<string>("RoleId")
                    .HasColumnType("TEXT");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("TEXT");

                b.Property<string>("LoginProvider")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .HasColumnType("TEXT");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens");
            });

        modelBuilder.Entity("RecipeUser", b =>
            {
                b.Property<Guid>("SharedRecipesId")
                    .HasColumnType("TEXT");

                b.Property<string>("SharedWithId")
                    .HasColumnType("TEXT");

                b.HasKey("SharedRecipesId", "SharedWithId");

                b.HasIndex("SharedWithId");

                b.ToTable("RecipeUser");
            });

        modelBuilder.Entity("Kokbok.Api.Models.ExactValue", b =>
            {
                b.HasBaseType("Kokbok.Api.Models.AmountValue");

                b.Property<double>("Value")
                    .HasColumnType("REAL");

                b.HasDiscriminator().HasValue("exact");
            });

        modelBuilder.Entity("Kokbok.Api.Models.RangeValue", b =>
            {
                b.HasBaseType("Kokbok.Api.Models.AmountValue");

                b.Property<double>("From")
                    .HasColumnType("REAL");

                b.Property<double>("To")
                    .HasColumnType("REAL");

                b.HasDiscriminator().HasValue("range");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Images", b =>
            {
                b.HasBaseType("Kokbok.Api.Models.Source");

                b.HasDiscriminator().HasValue("images");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Link", b =>
            {
                b.HasBaseType("Kokbok.Api.Models.Source");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasDiscriminator().HasValue("link");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Pdf", b =>
            {
                b.HasBaseType("Kokbok.Api.Models.Source");

                b.Property<Guid>("AssetId")
                    .HasColumnType("TEXT");

                b.HasIndex("AssetId");

                b.ToTable("Source", t =>
                    {
                        t.Property("AssetId")
                            .HasColumnName("Pdf_AssetId");
                    });

                b.HasDiscriminator().HasValue("pdf");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Plaintext", b =>
            {
                b.HasBaseType("Kokbok.Api.Models.Source");

                b.Property<Guid>("AssetId")
                    .HasColumnType("TEXT");

                b.HasIndex("AssetId");

                b.HasDiscriminator().HasValue("plaintext");
            });

        modelBuilder.Entity("AssetImages", b =>
            {
                b.HasOne("Kokbok.Api.Models.Asset", null)
                    .WithMany()
                    .HasForeignKey("AssetsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Kokbok.Api.Models.Images", null)
                    .WithMany()
                    .HasForeignKey("ImagesId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Kokbok.Api.Models.Asset", b =>
            {
                b.HasOne("Kokbok.Api.Models.User", "UploadedBy")
                    .WithMany("Assets")
                    .HasForeignKey("UploadedById")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("UploadedBy");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Ingredient", b =>
            {
                b.HasOne("Kokbok.Api.Models.Section<Kokbok.Api.Models.Ingredient>", null)
                    .WithMany("Values")
                    .HasForeignKey("SectionId");

                b.OwnsOne("Kokbok.Api.Models.Amount", "Amount", b1 =>
                    {
                        b1.Property<Guid>("IngredientId")
                            .HasColumnType("TEXT");

                        b1.Property<string>("Unit")
                            .HasColumnType("TEXT");

                        b1.Property<Guid>("ValueId")
                            .HasColumnType("TEXT");

                        b1.HasKey("IngredientId");

                        b1.HasIndex("ValueId");

                        b1.ToTable("Ingredient");

                        b1.WithOwner()
                            .HasForeignKey("IngredientId");

                        b1.HasOne("Kokbok.Api.Models.AmountValue", "Value")
                            .WithMany()
                            .HasForeignKey("ValueId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();

                        b1.Navigation("Value");
                    });

                b.Navigation("Amount");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Instruction", b =>
            {
                b.HasOne("Kokbok.Api.Models.Section<Kokbok.Api.Models.Instruction>", null)
                    .WithMany("Values")
                    .HasForeignKey("SectionId");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Recipe", b =>
            {
                b.HasOne("Kokbok.Api.Models.Asset", "Image")
                    .WithMany()
                    .HasForeignKey("ImageId");

                b.HasOne("Kokbok.Api.Models.User", "Owner")
                    .WithMany("OwnedRecipes")
                    .HasForeignKey("OwnerId");

                b.HasOne("Kokbok.Api.Models.Source", "Source")
                    .WithMany()
                    .HasForeignKey("SourceId");

                b.Navigation("Image");

                b.Navigation("Owner");

                b.Navigation("Source");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Section<Kokbok.Api.Models.Ingredient>", b =>
            {
                b.HasOne("Kokbok.Api.Models.Recipe", null)
                    .WithMany("Ingredients")
                    .HasForeignKey("RecipeId");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Section<Kokbok.Api.Models.Instruction>", b =>
            {
                b.HasOne("Kokbok.Api.Models.Recipe", null)
                    .WithMany("Instructions")
                    .HasForeignKey("RecipeId");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("Kokbok.Api.Models.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("Kokbok.Api.Models.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Kokbok.Api.Models.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("Kokbok.Api.Models.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("RecipeUser", b =>
            {
                b.HasOne("Kokbok.Api.Models.Recipe", null)
                    .WithMany()
                    .HasForeignKey("SharedRecipesId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Kokbok.Api.Models.User", null)
                    .WithMany()
                    .HasForeignKey("SharedWithId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Kokbok.Api.Models.Pdf", b =>
            {
                b.HasOne("Kokbok.Api.Models.Asset", "Asset")
                    .WithMany()
                    .HasForeignKey("AssetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Asset");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Plaintext", b =>
            {
                b.HasOne("Kokbok.Api.Models.Asset", "Asset")
                    .WithMany()
                    .HasForeignKey("AssetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Asset");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Recipe", b =>
            {
                b.Navigation("Ingredients");

                b.Navigation("Instructions");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Section<Kokbok.Api.Models.Ingredient>", b =>
            {
                b.Navigation("Values");
            });

        modelBuilder.Entity("Kokbok.Api.Models.Section<Kokbok.Api.Models.Instruction>", b =>
            {
                b.Navigation("Values");
            });

        modelBuilder.Entity("Kokbok.Api.Models.User", b =>
            {
                b.Navigation("Assets");

                b.Navigation("OwnedRecipes");
            });
#pragma warning restore 612, 618
    }
}
